#!/usr/bin/env python3
"""
png_to_rgb565.py — Convert a PNG to a C header for the ILI9341 display.

The ILI9341 on the BYUI eBadge expects RGB565 in little-endian byte order
(low byte first).  This script converts each pixel and byte-swaps it so
the C array can be transmitted directly over SPI without runtime conversion.

Usage
-----
    python png_to_rgb565.py <input.png> [output.h]

    input.png  — source image (will be resized to 320×240 if needed)
    output.h   — defaults to image_rgb565.h in the same folder

The output header defines:
    const uint16_t splash_image[320 * 240];
    #define SPLASH_IMAGE_W  320
    #define SPLASH_IMAGE_H  240

Requirements
------------
    pip install Pillow
"""

import sys
import os
from PIL import Image

TARGET_W = 320
TARGET_H = 240
VAR_NAME = "splash_image"


def rgb888_to_rgb565_le(r: int, g: int, b: int) -> int:
    """Return little-endian byte-swapped RGB565 uint16_t."""
    rgb565 = ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3)
    # Byte-swap so the SPI driver can transmit the uint16_t array raw.
    return ((rgb565 & 0x00FF) << 8) | ((rgb565 & 0xFF00) >> 8)


def convert(input_path: str, output_path: str) -> None:
    img = Image.open(input_path).convert("RGB")

    if img.size != (TARGET_W, TARGET_H):
        print(f"Resizing {img.size[0]}×{img.size[1]} → {TARGET_W}×{TARGET_H}")
        img = img.resize((TARGET_W, TARGET_H), Image.LANCZOS)
    else:
        print(f"Image is already {TARGET_W}×{TARGET_H} — no resize needed.")

    pixels = []
    for y in range(TARGET_H):
        for x in range(TARGET_W):
            r, g, b = img.getpixel((x, y))
            pixels.append(rgb888_to_rgb565_le(r, g, b))

    with open(output_path, "w") as f:
        f.write("/* Auto-generated by png_to_rgb565.py — do not edit manually. */\n")
        f.write("#pragma once\n")
        f.write("#include <stdint.h>\n\n")
        f.write(f"#define SPLASH_IMAGE_W  {TARGET_W}\n")
        f.write(f"#define SPLASH_IMAGE_H  {TARGET_H}\n\n")
        f.write(f"/* {TARGET_W * TARGET_H} pixels, "
                f"{TARGET_W * TARGET_H * 2} bytes, little-endian RGB565 */\n")
        f.write(f"static const uint16_t {VAR_NAME}"
                f"[{TARGET_W} * {TARGET_H}] = {{\n")

        cols = 12  # pixels per line
        for i, px in enumerate(pixels):
            if i % cols == 0:
                f.write("    ")
            f.write(f"0x{px:04X}")
            if i < len(pixels) - 1:
                f.write(", ")
            if i % cols == cols - 1 or i == len(pixels) - 1:
                f.write("\n")

        f.write("};\n")

    size_kb = TARGET_W * TARGET_H * 2 / 1024
    print(f"Written: {output_path}  ({size_kb:.1f} KB)")


if __name__ == "__main__":
    if len(sys.argv) < 2:
        print(f"Usage: python {os.path.basename(sys.argv[0])} <input.png> [output.h]")
        sys.exit(1)

    src = sys.argv[1]
    dst = sys.argv[2] if len(sys.argv) > 2 else os.path.join(
        os.path.dirname(os.path.abspath(sys.argv[0])), "image_rgb565.h"
    )

    convert(src, dst)
